### ISSUE TITLE
Analyse CSA

### ISSUE THREAD

**Issue by sandrinebedard** [sct-pipeline/contrast-agnostic-softseg-spinalcord#27] opened 2022-08-15 15:14 UTC
# Description

The aim of the project is to get a smaller variaion of CSA across contrast then what we have on the GT.

The idea is to create a python script to analyse the output csv files with CSA.

## CSA analysis of each training variation
- STD of CSA across 6 contrast persubject
- Mean (STD)
- Violin plot: of hard and soft GT

## Impact of other factors:

- Contrast-agnostic
- Impact of soft averaged labels
- Non-binarization

**Comment by ebadrian** [comment] 2022-08-17 16:37
Associated [PR](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/pull/30).

I created a preliminary notebook to visualize charts of interest with mock data. Currently we assume that we have a single `pandas.Dataframe` object containing all contrasts' CSA for each method. 
There are currently 2 valid type of charts:

- Violin plots: Individual contrast performance against a reference contrast for each method. These charts aim to showcase any bias of a specific contrast CSA value against the reference contrast CSA value. We use the pair-wise difference (in % w.r.t reference contrast) for the comparison.
<img width="974" alt="Capture d’écran 2022-08-17 à 14 42 54" src="https://user-images.githubusercontent.com/62891524/185190853-1522fea5-4c2c-48e4-b714-455525c6ef25.png">

- Violin plot: Methods' performance across contrasts using a measure of dispersion. Currently, the dispersion measure used is the standard deviation of all contrasts' CSA for each patient, for a given method. This chart aims to showcase the performance in CSA bias mitigation across contrasts of each method/baseline.
<img width="725" alt="Capture d’écran 2022-08-17 à 14 43 14" src="https://user-images.githubusercontent.com/62891524/185190757-50679c5e-ed33-465d-b947-7727ebfc41c9.png">

---
### TODOs:

- [ ] A function that merges the intermediate sub-csv files. We assume that we will have one csv file per contrast. Each of these csv files will contain all CSA values of said contrast predicted/GT segmentation masks. 
- [ ] A python script to run that will create all the charts once given the data folder containing all of these sub-csv files.

**Comment by naga-karthik** [comment] 2023-11-09 19:30
@sandrinebedard this issue seems to be very old. Could you close the issue after you have confirmed? Thanks!

**Closed** 2023-11-10 20:20 UTC
